apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlb-tls-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging # Ingress-shim
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.rlawnsdud.shop
    secretName: demo-rlawnsdud-shop-tls
  rules:
  - host: demo.rlawnsdud.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-svc
            port:
              number: 80
